name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build veerakumarmail/docker-node-sample . --file Dockerfile --tag my-image-name:$(date +%s)
      run: docker push veerakumarmail/docker-node-sample     
